APP_NAME = "FilePilot"
APP_VERSION = "1.0.0"
APP_DEVELOPER = "Sadi Al-lulu"
APP_TAGLINE = "Smart desktop file automation and organization system."
APP_COPYRIGHT = "© 2026 All rights reserved."
APP_WEBSITE = "	sadii.allulu@gmail.com"
APP_EMAIL = "sadii.allulu@gmail.com"