from __future__ import annotations

import re
from dataclasses import dataclass

from app.product_identity import PRODUCT_IDENTITY, ProductIdentity


_VERSION_PATTERN = re.compile(r"^(\d+)\.(\d+)\.(\d+)(?:\+([a-z0-9.-]+))?$")
_CHANNEL_COMPONENTS = {"release": 0, "development": 1}


@dataclass(frozen=True)
class WindowsVersionMetadata:
    numeric: tuple[int, int, int, int]
    display: str

    @property
    def numeric_string(self) -> str:
        return ".".join(str(component) for component in self.numeric)


def windows_version_metadata(
    identity: ProductIdentity = PRODUCT_IDENTITY,
) -> WindowsVersionMetadata:
    """Map display identity to Windows' required four numeric components."""
    match = _VERSION_PATTERN.fullmatch(identity.version)
    if match is None:
        raise ValueError(f"Unsupported product version: {identity.version!r}")
    major, minor, patch = (int(value) for value in match.groups()[:3])
    if identity.channel not in _CHANNEL_COMPONENTS:
        raise ValueError(f"Unsupported release channel: {identity.channel!r}")
    numeric = (major, minor, patch, _CHANNEL_COMPONENTS[identity.channel])
    if any(component < 0 or component > 65535 for component in numeric):
        raise ValueError("Windows version components must be between 0 and 65535")
    return WindowsVersionMetadata(numeric=numeric, display=identity.display_version)


def render_pyinstaller_version_file(
    identity: ProductIdentity = PRODUCT_IDENTITY,
) -> str:
    metadata = windows_version_metadata(identity)
    numeric = repr(metadata.numeric)
    product_name = identity.product_name
    original_filename = f"{product_name}.exe"
    return f"""# Generated by build.py from app.product_identity.PRODUCT_IDENTITY.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={numeric},
    prodvers={numeric},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('FileDescription', '{product_name} desktop application'),
         StringStruct('FileVersion', '{metadata.numeric_string}'),
         StringStruct('InternalName', '{product_name}'),
         StringStruct('OriginalFilename', '{original_filename}'),
         StringStruct('ProductName', '{product_name}'),
         StringStruct('ProductVersion', '{metadata.display}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
